### ISSUE TITLE
Which dev tool?

### ISSUE THREAD

**Issue by bradleyl** [ine-rmotr-projects/itp-simple-calculator#11]
I've just finished the Rmotr Intro to functions Simple calculator exercise. The next exercise just takes me to Github.  Is there an on line development tool I'm supposed to use?  If so, please send me the link.

**Comment by santiagobasulto** [comment]
Hello Bradley! Yes, you can use [notebooks.ai](https://notebooks.ai). Just create a new project and paste the URL of this repository to get started. I'll create a quick sample video.

**Comment by santiagobasulto** [comment]
Here's a quick guide: https://youtu.be/bOlyEOyFeQI
